/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'panel': RouteRecordInfo<'panel', '/panel', Record<never, never>, Record<never, never>>,
    'panel-cosmetic-brands': RouteRecordInfo<'panel-cosmetic-brands', '/panel/cosmetic/brands', Record<never, never>, Record<never, never>>,
    'panel-furniture-category': RouteRecordInfo<'panel-furniture-category', '/panel/furniture/category', Record<never, never>, Record<never, never>>,
    'panel-furniture-category-id': RouteRecordInfo<'panel-furniture-category-id', '/panel/furniture/category/:id()', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'panel-furniture-orders': RouteRecordInfo<'panel-furniture-orders', '/panel/furniture/orders', Record<never, never>, Record<never, never>>,
  }
}
